version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: 'yarn install --pure-lockfile --no-progress'
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: test
          command: 'yarn test'
      - run:
          name: build
          command: 'yarn build'
      - run:
          name: zip dist
          command: 'cd dist && zip -r9 ../grafana-plotly-panel-dev.zip *'
      - store_artifacts:
          path: grafana-plotly-panel-dev.zip
